version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    image: auxo_assesment
    command: /start.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
   